package com.app.mmm.enums;

public enum ComplaintType {

	GARBAGE_MANAGEMENT, 
	WATER_SUPPLY, 
	ELECTRICITY_MANAGEMENT, 
	ROAD_REPAIR, 
	SANITATION_ISSUES,
	TRAFFIC_MANAGEMENT,
	ENVIRONMENTAL_HAZARDS,
	FIRE_SAFETY
}
